### ISSUE TITLE
Cleanup repo

### ISSUE THREAD

**Issue by kylepjohnson** [cltk/marathi_text_wikisource#1]
- remove `.idea` from this repo
- In the README, make a list of other Classics texts from before mid-19th century

Thanks!

**Comment by kylepjohnson** [comment]
Pinging @MaheshBhosale 

Please also remove `virtualenv`

**Comment by bhosalems** [comment]
Things are done as required. Should I proceed to close the issue?
Thanks!

**Comment by kylepjohnson** [comment]
Thank you!
