### ISSUE TITLE
Using a class 

### ISSUE THREAD

**Issue by shantanuo** [cltk/marathi_text_wikisource#6]
Since the functions like 'get_html' and 'create_directory' are common across all scripts, we need to write a single class for this. 
Use decorator for _write function to add a new source. This python package will be extensible and anyone can add a new source by writing a single function.

**Comment by bhosalems** [comment]
That seems a good proposal. Would you work on this?

**Comment by bhosalems** [comment]
Have you thought of something, or would converse with your idea? Anyways, otherwise, I will put an eye on nitty-gritty details of decorator online.
