### ISSUE TITLE
Tukaram Gatha

### ISSUE THREAD

**Issue by solegaonkar** [cltk/marathi_text_wikisource#7]
I landed here, looking for Tukaram Gatha. This is the best collection I have seen so far. But the 4500-4800 is still pending.
If you know a source and just short of  time,.. If you can give some pointers, I would like to assist you in completing it. 

Thanks!

**Comment by bhosalems** [comment]
https://mr.wikisource.org/wiki/%E0%A4%AE%E0%A5%81%E0%A4%96%E0%A4%AA%E0%A5%83%E0%A4%B7%E0%A5%8D%E0%A4%A0

You can take a look at the scrapping scripts, and write them to include a new dataset. There were proposals of creating a class altogether and making it more accessible to people to add more Marathi literature datasets, I couldn't find much time to work before and unfortunately happen not to have time at my disposal right now.
